name: bare_codegen_example
description: A package consuming bare_codegen
  
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
    bare: 
      path: ../bare/

dev_dependencies:
  build_runner: ^2.1.8
  bare_codegen:
    path: ../bare_codegen/
  test: "^1.16.2"
  hex: ^0.2.0
