name: bare
description: A BARE library for Dart. An encoding/decoding BARE implementation.
version: 0.1.0-dev.1
homepage: https://github.com/kaashyapan/bare-dart

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  typed_data: "^1.3.0"
  convert: "^3.0.0"
  meta: "^1.3.0"
  fixnum: ^1.0.0

dev_dependencies:
  test: "^1.16.2"
  pedantic: "^1.10.0"
  hex: ^0.2.0
