name: bare_codegen
description: Code generator to covert BARE schema to Dart classes
version: 0.1.1
homepage: https://github.com/kaashyapan/bare-dart
repository: https://github.com/kaashyapan/bare-dart


environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  build: ^2.2.1
  intl: ^0.17.0
  petitparser: ^5.0.0
  recase: ^4.0.0
  dart_style: ^2.2.2

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.1.8
  test: ^1.20.2
