name: bare
description: A BARE library for Dart. An encoding/decoding BARE implementation.
version: 0.1.0-dev.3
homepage: https://github.com/kaashyapan/bare-dart
repository: https://github.com/kaashyapan/bare-dart
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.14.0-0 <3.0.0"

dependencies:
  fixnum: ^1.0.0

dev_dependencies:
  test: "^1.16.2"
  collection: ^1.16.0
  hex: ^0.2.0
